apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: api-deployment
  labels: 
    app: api
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: api
  template: 
    metadata: 
      labels: 
        app: api
    spec: 
      containers: 
      - name: api
        # TODO: point this at our image registry (once the latte
        #  images are being built and pushed there)
        image: testcontainers/helloworld

---

apiVersion: v1 
kind: Service 
metadata: 
  name: api-service
spec: 
  selector: 
    app: api
  ports: 
    - port: 9999
      targetPort: 9999